feedbacksystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mysite.urls')),
]

mysite/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'mysite'
urlpatterns = [
    path('', views.feedback_form, name='form'),
    path('try_to_connect', views.try_to_connect),
    path('create', views.feedback_create, name='create'),
    # path(r'^detail/(?P<id>\d+)/$', views.feedback_detail),
    path('detail/<int:pk>/', views.feedback_detail , name='detail'),
    path('update/<int:pk>/', views.feedback_update, name='update'),
    path('delete/<int:pk>/', views.feedback_delete),
]

mysite/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# form django.core.urlresolvers import reverse
# Create your models here.
class Subject(models.Model):
    subject_name = models.CharField(max_length=10)

    def __str__(self):
        return self.subject_name


class Teacher(models.Model):
    teacher_name = models.CharField(max_length=30)

    def __str__(self):
        return self.teacher_name

class TeacherSubjectMapping(models.Model):
    teacher_name = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    subject_name = models.ForeignKey(Subject, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.teacher_name}-{self.subject_name}"

class Section(models.Model):
    Section_name = models.CharField(max_length=3)
    subject_name = models.ManyToManyField(TeacherSubjectMapping)
    def __str__(self):
        return self.Section_name

# S09 Naman Sharma 3215603116 Mr. Ashish MATHS 2016
class Feedback(models.Model):
    student_name = models.CharField(max_length=120, default='Naman Sharma')
    rollno = models.IntegerField(default='03215603116')

    Section_name = models.ForeignKey(Section, on_delete=models.CASCADE, default='S09')
    teacher_name = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    teacher_subject = models.ForeignKey(Subject, on_delete=models.CASCADE)

    batch = models.IntegerField(validators=[
        MaxValueValidator(2100),
        MinValueValidator(2000),
    ], default='2016')

    Punctuality = models.IntegerField(blank=False, validators=[
        MaxValueValidator(5),
        MinValueValidator(1),
    ])
    Subject_knowledge = models.IntegerField(blank=False, validators=[
        MaxValueValidator(5),
        MinValueValidator(1),
    ])
    Behaviour = models.IntegerField(blank=False, validators=[
        MaxValueValidator(5),
        MinValueValidator(1),
    ])
    Method_of_teaching = models.IntegerField(blank=False, validators=[
        MaxValueValidator(5),
        MinValueValidator(1),
    ])
    Audibility = models.IntegerField(blank=False, validators=[
        MaxValueValidator(5),
        MinValueValidator(1),
    ])
    Syllabus_coverage = models.IntegerField(blank=False, validators=[
        MaxValueValidator(5),
        MinValueValidator(1),
    ])

    def get_absolute_url(self):
        return "/detail/%s/" %(self.id)
        # return reverse("detail", kwargs ={"id":self.id})

    def __str__(self):
        return f"{str(self.Section_name)}-{str(self.teacher_name)}-{str(self.teacher_subject)}"

mysite/forms.py
from django import forms

from .models import Feedback


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        exclude = []
        #exclude = ['student_name','rollno','batch','Section_name']

mysite/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .forms import FeedbackForm

from .models import Feedback
from django.contrib import messages

def feedback_form(request):
    form = FeedbackForm(request.POST or None)
    if form.is_valid():
        instance = form.save()
        instance.save()
        messages.success(request,"Successfully Created.")
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {"form":form}
    return render(request, 'mysite/feedback_form.html',context)
    # if request.method == 'POST':
    #     form = FeedbackForm(request.POST)
    #     context = {"form":form}
    #     if form.is_valid():
    #         form.save()
    #         return render(request, 'mysite/thanks.html',context)
    # else:
    #     form = FeedbackForm()
    # return render(request, 'mysite/feedback_form.html', {'mysite': form})

def try_to_connect(request):
    return render(request,'mysite/index.html')






def feedback_create(request):
    queryset = Feedback.objects.all()
    context = {"objectList":queryset,
    "title":'create'}
    # if request.user.is_authenticated():
    #     context = {"title":"create"}
    # else :
        # context = {"title":"invalid create"}
    return render(request,'mysite/core.html',context)

def feedback_detail(request, pk):
    instance = get_object_or_404(Feedback,pk=pk)
    context = {"Section":instance.Section_name,
    "instance":instance}
    return render(request,'mysite/detail.html',context)

def feedback_update(request, pk=None):
    instance = get_object_or_404(Feedback,pk=pk)
    form = FeedbackForm(request.POST or None, instance = instance)
    if form.is_valid():
        instance = form.save()
        instance.save()
        messages.success(request,"Successfully updated.")
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {"form":form,
    "instance":instance}
    return render(request,'mysite/detail.html',context)

def feedback_delete(request, pk):
    instance = get_object_or_404(Feedback,pk=pk)
    instance.delete()
    messages.success(request,"Successfully deleted.")
    return redirect("mysite:create")

mysite/templates/mysite/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block body %}{% endblock %}
</body>
</html>

mysite/templates/mysite/core.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}create{% endblock title %}</title>
  </head>
  <body>
    <div class='container'>
      {% block content%}


          <h1>{{title}} is working!</h1>

          {% for obj in objectList %}

           {{obj.Section_name}}
           {{obj.student_name}}
           <a href='{{obj.get_absolute_url}}'>{{obj.rollno}}</a>
           {{obj.teacher_name}}
           {{obj.teacher_subject}}
           {{obj.batch}}

           <br>
          {% endfor %}

      {% endblock content %}

  </body>
</html>

mysite/templates/mysite/detail.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>create</title>
  </head>
  <body>
    <!-- { if messages %}
<ul class="messages">
    { for message in messages }
    <li{ if message.tags } class="{ message.tags }"{ endif }>
        { if message.level == DEFAULT_MESSAGE_LEVELS.ERROR }Important: { endif }
        { message }
    </li>
    { endfor }
</ul>
{ endif } -->

    <h1>{{instance}} is working!</h1>
    {{instance.Section_name}}
    {{instance.student_name}}
     {{instance.rollno}}
     {{instance.teacher_name}}
     {{instance.teacher_subject}}
     {{instance.batch}}
     <br>
  </body>
</html>

mysite/templates/mysite/feedback_form.html
{% extends 'mysite/core.html' %}

{% block content %}
<!-- { block.super } -->
<!-- Navigation -->
    <nav class="navbar navbar-expand-lg bg-secondary fixed-top text-uppercase" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#">Start Bootstrap</a>
        <button class="navbar-toggler navbar-toggler-right text-uppercase bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#">Portfolio</a>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#">About</a>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav> 
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <!-- form.as_table -->
  <input type="submit" />
</form>
{% endblock content %}

mysite/templates/mysite/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>feedback_form</title>
  </head>
  <body>
    <h1>this is the feedback_form page!.</h1>
    <form action="" method="POST">
    {% csrf_token %}
    {{ formset.FeedbackForm }}
    <table border="1">
      <tr>
        <th>Teacher Name</th>
        <th>Subject Name</th>
        <th>Punctuality</th>
        <th>Subject Knowledge</th>
        <th>Discipline/Behavior</th>
        <th>Methodology of teaching</th>
        <th>Communication/audibility</th>
        <th>Syllabus Coverage</th>
      </tr>
      {% for teacher, form in Iterators %}
          <tr>
            <td>{{ teacher.teacher_name }}</td>
            <td>{{ teacher.subject_name }}</td>
            {% for field in form %}
                <td>
                  <table>
                    <tr>
                      {% for radio in field %}
                          <td>{{ radio }}</td>
                      {% endfor %}
                    </tr>
                    <tr>
                      {% for radio in field %}
                          <td>{{ radio.data.value }}</td>
                      {% endfor %}
                    </tr>
                  </table>
                </td>
            {% endfor %}
          </tr>
      {% endfor %}
    </table>
    <input type="submit" value="Submit">
</form>
  </body>
</html>

mysite/templates/mysite/thanks.html
{% extends 'mysite/core.html' %}

{% block title %}Thanks{% endblock %}

{% block body %}
<h1>Thanks for your response.</h1>
<p><a href="{% url 'mysite:form' %}">Response again?</a></p>
{% endblock %}